package com.ironhabit.app

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.ironhabit.app.data.local.AppDatabase
import com.ironhabit.app.data.local.entity.ExerciseEntity
import com.ironhabit.app.data.local.entity.WeekPlanEntity
import com.ironhabit.app.domain.model.ExerciseCategory
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.flow.first
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.fail
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * `WeekPlanDao.upsertExplicit` 行为测试（内存库，[allowMainThreadQueries]）。
 *
 * 重点回归 v1.8 修复：upsert 必须先按**主键 id** 匹配，否则编辑已有计划时换动作/换星期
 * 会落到 `insert(entity)`（entity.id 仍是旧主键）→ 主键冲突抛异常、"保存失败"。
 */
@RunWith(AndroidJUnit4::class)
class WeekPlanDaoUpsertTest {

    private lateinit var database: AppDatabase

    @Before
    fun setUp() {
        val context: Context = ApplicationProvider.getApplicationContext()
        database = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
    }

    @After
    fun tearDown() {
        database.close()
    }

    private suspend fun insertExercise(name: String): Long =
        database.exerciseDao().upsert(
            ExerciseEntity(name = name, category = ExerciseCategory.STRENGTH),
        )

    /** 编辑已有计划并**换动作**：修复后应按主键更新、不抛异常、动作改成功。 */
    @Test
    fun editingPlanAndChangingExerciseUpdatesByIdWithoutCrash() = runBlocking {
        val exA = insertExercise("深蹲")
        val exB = insertExercise("硬拉")

        val planId = database.weekPlanDao().insert(
            WeekPlanEntity(exerciseId = exA, dayOfWeek = 1, targetSets = 3, targetReps = 12),
        )
        assertNotNull(planId)

        // 编辑：换动作 exA → exB（同一天），主键保持 planId
        val updated = WeekPlanEntity(
            id = planId,
            exerciseId = exB,
            dayOfWeek = 1,
            targetSets = 4,
            targetReps = 8,
        )
        val returnedId = database.weekPlanDao().upsertExplicit(updated)
        assertEquals(planId, returnedId)

        val row = database.weekPlanDao().getById(planId)
        assertEquals("换动作后应写入 exB", exB, row?.exerciseId)
        assertEquals(4, row?.targetSets)
    }

    /** 纯新增（id=0）应走自增插入，拿到非零 id。 */
    @Test
    fun addingNewPlanInsertsWithAutogeneratedId() = runBlocking {
        val exA = insertExercise("卧推")

        val newId = database.weekPlanDao().upsertExplicit(
            WeekPlanEntity(exerciseId = exA, dayOfWeek = 2, targetSets = 5, targetReps = 10),
        )
        assert(newId > 0) { "新增计划应拿到自增主键，实际 $newId" }
        assertEquals(1, database.weekPlanDao().observeAll().first().size)
    }

    /** 新增命中软删行占用的槽位 → 复活（UPDATE），不抛异常。 */
    @Test
    fun addingIntoSoftDeletedSlotReactivatesIt() = runBlocking {
        val exA = insertExercise("高位下拉")
        val planId = database.weekPlanDao().insert(
            WeekPlanEntity(exerciseId = exA, dayOfWeek = 3, targetSets = 3, targetReps = 12),
        )
        database.weekPlanDao().softDelete(planId) // is_active = 0，但唯一槽位仍占用

        val returnedId = database.weekPlanDao().upsertExplicit(
            WeekPlanEntity(exerciseId = exA, dayOfWeek = 3, targetSets = 4, targetReps = 10),
        )
        assertEquals(planId, returnedId)
        val row = database.weekPlanDao().getById(planId)
        assertEquals(true, row?.isActive) // 已复活
        assertEquals(4, row?.targetSets)
    }

    /** 编辑时把动作改到**另一条计划已占用**的槽位 → 应抛 UNIQUE 冲突（VM 会转成友好提示）。 */
    @Test
    fun editingIntoOccupiedSlotThrowsConstraint() = runBlocking {
        val exA = insertExercise("二头弯举")
        val exB = insertExercise("三头下压")
        // 同天两条不同动作的计划
        database.weekPlanDao().insert(
            WeekPlanEntity(exerciseId = exA, dayOfWeek = 4, targetSets = 3, targetReps = 12),
        )
        val planB = database.weekPlanDao().insert(
            WeekPlanEntity(exerciseId = exB, dayOfWeek = 4, targetSets = 3, targetReps = 12),
        )

        // 把 planB 改到 exA 占用的 (天=4, 动作=exA) → 冲突
        try {
            database.weekPlanDao().upsertExplicit(
                WeekPlanEntity(id = planB, exerciseId = exA, dayOfWeek = 4, targetSets = 3, targetReps = 12),
            )
            fail("应抛出 UNIQUE 冲突异常")
        } catch (_: android.database.sqlite.SQLiteConstraintException) {
            // 预期：主键不匹配目标槽位 → UNIQUE 冲突
        }
    }
}
